[project]
name = "afsesab-rest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.135.1",
    "httpx>=0.28.1",
    "mkdocstrings>=1.0.3",
    "mkdocstrings-python>=2.0.3",
    "pandas>=3.0.1",
    "psycopg>=3.3.3",
    "sqlalchemy>=2.0.47",
    "ttkbootstrap>=1.20.1",
    "uvicorn>=0.41.0",
    "zensical>=0.0.24",
]

[tool.uv.workspace]
members = [
    "uv",
]

[dependency-groups]
dev = [
    "zensical>=0.0.24",
]
