[project]
name = "afsesab-middleware"
version = "0.1.0"
description = "Aplicação robusta desenvolvida em Python que atua como um nó logístico e interface gráfica desktop para unidades de saúde"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.135.1",
    "httpx>=0.28.1",
    "mkdocstrings[python]>=1.0.3",
    "pandas>=3.0.1",
    "psycopg>=3.3.3",
    "sqlalchemy>=2.0.47",
    "ttkbootstrap>=1.20.1",
    "uvicorn>=0.41.0",
    "zensical>=0.0.24",
]

[tool.uv.workspace]
members = [
    "uv",
]
