name: ci
on:
    push:
        branches:
            - master
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Instalar o uv
              uses: astral-sh/setup-uv@v2

            - name: Instalar Python e Dependências
              run: uv python install && uv sync

            - name: Realizar o Deploy no GitHub Pages
              run: uv run mkdocs gh-deploy --force
