name: ci
on:
    push:
        branches:
            - master
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Instalar o uv
              uses: astral-sh/setup-uv@v2

            - name: Instalar Python e Dependências
              run: uv python install && uv sync

            - name: Compilar a Documentação (Zensical Build)
              # Ao invés de gh-deploy, nós apenas mandamos ele construir o HTML.
              # Ele vai gerar uma pasta "./site" [2].
              run: uv run zensical build

            - name: Realizar o Deploy no GitHub Pages
              # Usamos uma Action nativa dedicada para empurrar a pasta "site" para a branch "gh-pages"
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./site
                  force_orphan: true
