name: Documentation

on:
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true
                  cache-dependency-path: "uv.lock"

            - name: Set up Python
              run: uv python install 3.12 # Versão estável recomendada para MkDocs/Zensical

            - name: Install dependencies
              # O uv instala o zensical e mkdocstrings instantaneamente
              run: |
                  uv pip install zensical mkdocstrings[python]

            - name: Build documentation
              # 'uv run' garante que o zensical use o ambiente virtual correto
              run: uv run zensical build --clean
              env:
                  GITHUB_PAGES: true

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./site

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
